version: '2'

services:
  glassfish:
    image: glassfish
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:4848:4848"
    container_name: glassfish
    volumes:
      - ./target:/usr/local/glassfish4/glassfish/domains/domain1/autodeploy/
  mypostgres:
    image: postgres
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=split_temp_pwd
     - POSTGRES_USER=postgres
     - POSTGRES_DB=splitdb
